name: Invite Member on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  invite_member:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check if User is Already a Member
        id: check_membership
        env:
          ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" -s -L \
            -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/orgs/$ORGANIZATION_NAME/members/${{ github.event.pull_request.user.login }}")

          if [[ "$STATUS" -eq 204 ]]; then
            echo "User is already a member. Skipping invitation."
            echo "IS_MEMBER=true" >> $GITHUB_ENV
          else
            echo "User is not a member. Proceeding with invitation."
            echo "IS_MEMBER=false" >> $GITHUB_ENV
          fi

      - name: Invite Members
        if: env.IS_MEMBER == 'false'
        env:
          ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "Inviting ${{ github.event.pull_request.user.login }} to $ORGANIZATION_NAME..."
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORGANIZATION_NAME/invitations \
            -d "{\"invitee_id\": ${{ github.event.pull_request.user.id }}, \"role\":\"direct_member\"}")

          if [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to invite user. GitHub API Response:"
            cat response.json
            exit 1
          else
            echo "User successfully invited! 🎉"
          fi
