name: Check Membership Onboarding Automation Workflow

on:
  pull_request:
    paths:
      - ".github/workflows/invite.yml"

jobs:
  check-invite-modification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if invite.yml was modified
        run: |
          echo "The file .github/workflows/invite.yml was modified in this PR."
      
      - name: Report Success
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{"state": "success", "context": "check-invite-modification", "description": "Invite.yml check passed"}'


